var refreshAdvertise = function(){
    $.ajax({
    	"type": "POST",
    	"url": "<!--{base}-->/twitter/Advertise.json",
    	"data": {
    		"account_id": "<!--{$attr.account->account_id}-->"
    	},
    	"dataType": "jsonp",
    	"success": function(data){
    		reloadAdvertise(data);
    	}
    });
};

var reloadAdvertise = function(data){
	$("#advertises").html("");
	for(var i in data){
		var icon = $("<span />").attr("id", "delete_" + data[i].tweet_advertise_id).addClass("glyphicon").addClass("glyphicon-remove");
		icon.click(function(){
   	        $.ajax({
   	        	"type": "POST",
   	        	"url": "<!--{base}-->/twitter/Advertise.json",
   	        	"data": {
   	        		"mode": $(this).attr("id")
   	        	},
   	        	"dataType": "jsonp",
   	        	"success": function(data){
   	        		reloadAdvertise(data);
   	        	}
   	        });
		});
		var text = $("<td />").addClass("col-md-10").text(data[i].advertise_text);
    	$("<tr />").append($("<td />").addClass("col-md-2").append(icon)).append(text).appendTo("#advertises");
    }
}

$("#add_advertise").click(function(){
    $.ajax({
    	"type": "POST",
    	"url": "<!--{base}-->/twitter/Advertise.json",
    	"data": {
    		"account_id": "<!--{$attr.account->account_id}-->",
    		"text": $("#advertise_text").val()
    	},
    	"dataType": "jsonp",
    	"success": function(data){
    		reloadAdvertise(data);
    	}
    });
});
